################################################################################
## General options and configurations for the grid-based MMS testing cases
################################################################################
mms_configurations:
  subdir: grid
  reference_dir: references
  geometries: [slab, circular, salpha, dommaschk]
  n_resolutions: 4
  scaling_factor: 2

  vars_to_upscale:
    params_mesh: [n_levels, n_points_phi, n_points_vp, n_points_mu]
    params_time_loop: [n_timesteps, steps_diagnostics]

  vars_to_downscale:
    params_mesh: [spacing_RZ]
    params_time_loop: [dt]

  max_limits:
    n_points_mu: 24

  min_limits:

  file_dependencies:
    - parameters.yml
    - job_configurations_grid.yml

  file_dependencies_dir: configurations
