from __future__ import annotations

import importlib.util
import json
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
INPUT = ROOT / "fixtures/stella_w7x_mode_structure_run/stella_w7x_adiabatic_electrons.in"


SYNTHETIC_EXPLICIT_SOURCE = """\
module gyrokinetic_equation_explicit
   private
contains
   subroutine add_explicit_gyrokinetic_terms
      use parallelisation_layouts, only: vmu_lo
      complex, dimension(:, :), allocatable :: rhs_ky_swap
      restart_time_step = .false.
      call advance_mirror_explicit(pdf, rhs)
      call advance_wdrifty_explicit(pdf, phi, bpar, rhs)
      call advance_wdriftx_explicit(pdf, phi, bpar, rhs)
      call advance_wstar_explicit(phi, rhs)
      call advance_parallel_streaming_explicit(pdf, phi, bpar, rhs)
      ! if advancing apar, need to convert input pdf back from g to gbar
   end subroutine add_explicit_gyrokinetic_terms
   !****************************************************************************
   !                                      Title
end module gyrokinetic_equation_explicit
"""


def _write_synthetic_explicit_source(path: Path) -> None:
    path.write_text(SYNTHETIC_EXPLICIT_SOURCE, encoding="utf-8")


def _load_module():
    path = ROOT / "scripts/prepare_stella_w7x_rhs_trace_run.py"
    spec = importlib.util.spec_from_file_location("prepare_stella_w7x_rhs_trace_run", path)
    assert spec is not None
    assert spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def test_stella_explicit_rhs_trace_patch_is_focused_and_idempotent(tmp_path: Path):
    module = _load_module()
    source = tmp_path / "gyrokinetic_equation_explicit.f90"
    _write_synthetic_explicit_source(source)

    assert module.patch_stella_explicit_rhs_trace(
        source,
        trace_step=123,
        trace_iky=4,
        trace_ikx=1,
    )
    assert not module.patch_stella_explicit_rhs_trace(
        source,
        trace_step=123,
        trace_iky=4,
        trace_ikx=1,
    )
    text = source.read_text()

    assert "stellarator_gk W7-X ky=0.3 RHS trace patch" in text
    assert "integer, parameter :: stellarator_gk_trace_step = 123" in text
    assert "integer, parameter :: stellarator_gk_trace_iky = 4" in text
    assert "integer, parameter :: stellarator_gk_trace_ikx = 1" in text
    assert "stellarator_gk_trace_rhs_call = stellarator_gk_trace_rhs_call + 1" in text
    assert "use grids_velocity, only: vpa, mu, wgts_vpa, wgts_mu" in text
    assert "call stellarator_gk_write_complex_state('pdf_g', 'input_pdf', istep, pdf)" in text
    assert "call stellarator_gk_write_phi_trace(istep, phi)" in text
    assert "denominator_fields(stellarator_gk_trace_iky" in text
    assert "'quasineutrality', 'numerator'" in text
    assert "'quasineutrality', 'denominator'" in text
    assert "'normalization', 'native_state_scale'" in text
    assert "call stellarator_gk_write_rhs_delta('mirror_force'" in text
    assert "call stellarator_gk_write_rhs_delta('magnetic_drift_y'" in text
    assert "call stellarator_gk_write_rhs_delta('magnetic_drift_x'" in text
    assert "call stellarator_gk_write_rhs_delta('equilibrium_drive_wstar'" in text
    assert "call stellarator_gk_write_rhs_delta('parallel_streaming'" in text
    assert "call stellarator_gk_write_complex_state('rhs_total', 'total', istep, rhs)" in text
    assert "record step rhs_call term" in text
    assert "wgts_vpa wgts_mu code_time code_dt real imag" in text
    assert "wgts_vpa(iv), wgts_mu(1, iz, imu)" in text
    assert "rhs*dt" in text


def test_rhs_trace_input_uses_exact_nstep_stop(tmp_path: Path):
    module = _load_module()
    output = tmp_path / "rhs_trace.in"

    module.write_rhs_trace_input(
        INPUT,
        output,
        nstep=2000,
        delt=0.1,
        vmec_filename="wout_w7x.nc",
    )
    text = output.read_text()

    assert "Generated by scripts/prepare_stella_w7x_rhs_trace_run.py" in text
    assert "force_explicit_stream_mirror = true" in text
    assert "nstep = 2000" in text
    assert "tend = -1.0" in text
    assert "delt = 0.1" in text
    assert "nsave = 0" in text
    assert "save_for_restart = .false." in text
    assert "stream_implicit = F" in text
    assert "mirror_implicit = F" in text
    assert "mirror_semi_lagrange = F" in text
    assert "fully_explicit = T" in text
    assert "vmec_filename = 'wout_w7x.nc'" in text


def test_rhs_trace_input_can_preserve_implicit_stream_mirror(tmp_path: Path):
    module = _load_module()
    output = tmp_path / "rhs_trace_implicit.in"

    module.write_rhs_trace_input(
        INPUT,
        output,
        nstep=20,
        delt=0.1,
        vmec_filename="wout_w7x.nc",
        force_explicit_stream_mirror=False,
    )
    text = output.read_text()

    assert "force_explicit_stream_mirror = false" in text
    assert "stream_implicit = F" not in text
    assert "mirror_implicit = F" not in text
    assert "mirror_semi_lagrange = F" not in text
    assert "fully_explicit = T" not in text


def test_prepare_rhs_trace_run_writes_minimal_patched_tree(tmp_path: Path):
    module = _load_module()
    fake_source = tmp_path / "fake_stella"
    fake_explicit = fake_source / module.TARGET_RELATIVE_SOURCE
    fake_explicit.parent.mkdir(parents=True)
    _write_synthetic_explicit_source(fake_explicit)
    vmec = tmp_path / "wout_w7x.nc"
    vmec.write_bytes(b"fake-vmec")
    output_root = tmp_path / "prepared"

    prepared = module.prepare_stella_w7x_rhs_trace_run(
        stella_source=fake_source,
        input_file=INPUT,
        vmec_file=vmec,
        output_root=output_root,
        trace_step=20,
        tend=2.0,
        delt=0.1,
    )
    metadata = json.loads(prepared.metadata_file.read_text())
    patched_text = prepared.patched_explicit_source.read_text()

    assert prepared.trace_step == 20
    assert prepared.trace_iky == 4
    assert prepared.trace_ikx == 1
    assert metadata["status"] == "prepared_patched_stella_run_pending_execution"
    assert metadata["stella_source"] == str(fake_source)
    assert metadata["stella_source_revision"] == "unknown"
    assert metadata["stella_executable"].endswith(
        "stella/COMPILATION/build_cmake/COMPILATION/stella"
    )
    assert metadata["vmec_source"] == str(vmec)
    assert metadata["trace_step"] == 20
    assert metadata["rhs_units"] == "stella_native_rhs_times_code_dt"
    assert metadata["trace_format"] == "stellarator_gk_stella_rhs_trace_v3"
    assert metadata["velocity_weight_columns"] == ["wgts_vpa", "wgts_mu"]
    assert metadata["rhs_call_column"] == "rhs_call"
    assert metadata["force_explicit_stream_mirror"] is True
    assert metadata["trace_output"].endswith("stellarator_gk_w7x_ky03_rhs_trace.dat")
    assert prepared.build_script.read_text().startswith("#!/usr/bin/env bash")
    assert "STELLA_EXECUTABLE" in prepared.run_script.read_text()
    assert "integer, parameter :: stellarator_gk_trace_step = 20" in patched_text
    assert "nstep = 20" in prepared.input_file.read_text()
    assert "stream_implicit = F" in prepared.input_file.read_text()
