#!/usr/bin/env bash

# The bitwise or operation we use below requires the use of the gawk program
# and not other versions which might have the same alias awk but different
# features.
if ! [ -x "$(command -v gawk)" ]; then
    echo "${RED}Program 'gawk' could not be found${NC}. "\
         "Please install 'gawk' for the pre-commit check to run."
    exit 1
fi

# Colors for highlights
RED='\033[0;31m'   # red
BROWN='\033[0;33m' # Brown/dark yellow
NC='\033[0m'       # no color

len_err=false    # Error flag for lines too long
space_err=false  # Error flag for empty whitespace at the end of line
uel_err=false    # Error flag for unnecessary empty lines
tab_err=false    # Error flag for use of tabulator character

# Root directory of the local branch
root_dir=$(git rev-parse --show-toplevel)

# Apply only to file extensions specified by the following regex
extension_regex="^.*\.(f90|pf|cxx|hxx|cu|wls)$"

# Check type: staged, diff, or full. Checks either files which are staged for
# commit, all files with a diff, or all src files
check_type=${1:-"--staged"}
if [[ ${check_type} == "--staged" ]]; then
    files=$(git diff --staged --name-only \
            --line-prefix=`git rev-parse --show-toplevel`/ HEAD)
elif [[ ${check_type} == "--diff" ]]; then
    files=$(git diff --name-only \
            --line-prefix=`git rev-parse --show-toplevel`/ HEAD)
elif [[ ${check_type} == "--full" ]]; then
    files=$(find ${root_dir}/src/ -regextype posix-egrep \
            -regex ${extension_regex})
else
    echo -e "${RED}Error: ${BROWN}Option for check_type '$check_type'" \
            "not recognized, should be '--staged', '--diff', or '--full'!${NC}"
fi;

for f in $files; do

    if ! [[ $f =~ $extension_regex ]]; then continue; fi;

    # Find if any violations occur. We encode the possible violations in
    # binary, this lets us detect multiple different violation within the
    # same file.
    status=$(gawk 'BEGIN{x=0} \
                   /^.{81,}/{x=or(x,1)} \
                   /[ \t]+(\r?$)/{x=or(x,2)} \
                   /^$/{if(++i>1){x=or(x,4)}}/./{i=0} \
                   /^.*\t/{x=or(x,8)} \
                   END{print x}' $f)

    # If violation found, print file and each individual violation
    if [[ ${status} > 0 ]]; then
        echo -e "${RED}file: $f${NC}"

        if [[ $(($status & 1)) > 0 ]]; then
            awk -vNC=${NC} -vBROWN=${BROWN} \
                '/^.{81,}/{print BROWN, " line", NR, ":", NC, $0}' $f;
            len_err=true
        fi;
        if [[ $(($status & 2)) > 0 ]]; then
            awk -vNC=${NC} -vBROWN=${BROWN} -e\
                '/[ \t]+(\r?$)/{print BROWN, " line", NR, ":", NC, $0}' $f;
            space_err=true
        fi;
        if [[ $(($status & 4)) > 0 ]]; then
            awk -vNC=${NC} -vBROWN=${BROWN} \
                '/^$/{if(++i>1){print BROWN, " line", NR, ":", NC, \
                    "unnecessary empty line found"}}/./{i=0}' $f;
            uel_err=true
        fi;
        if [[ $(($status & 8)) > 0 ]]; then
            awk -vNC=${NC} -vBROWN=${BROWN} \
                '/^.*\t/{print BROWN, " line", NR, ":", NC, \
                    "illegal use of tabulator character"}' $f;
            tab_err=true
        fi;
    fi;
done

# Main hook to abort the commit
if ${len_err} || ${space_err} || ${uel_err} || ${tab_err}; then

    # Error messages
    if ${len_err}; then
        echo -e "${RED}Aborting commit${NC}: "\
                "The line length in source file is limited to 80 characters."
    fi
    if ${space_err}; then
        echo -e "${RED}Aborting commit${NC}: "\
                "Trailing whitespaces are not allowed."
    fi
    if ${uel_err}; then
        echo -e "${RED}Aborting commit${NC}: "\
                "More than one concurring empty line is not allowed."
    fi
    if ${tab_err}; then
        echo -e "${RED}Aborting commit${NC}: "\
                "Use of tabulator character is not allowed."
    fi

    exit 1
fi

exit 0
