#!/usr/bin/env bash

# Colors for highlights
GREEN='\033[0;32m' # Green
BROWN='\033[0;33m' # Brown/dark yellow
NC='\033[0m'       # No color

# Display bash version
echo -e "${BROWN}Bash version ${BASH_VERSION}${NC}"

# Store root directory of the local branch
root_dir=$(git rev-parse --show-toplevel)

# Store directory of predefined git-hooks
hook_dir="${root_dir}/.git-hooks"

# Store the predefined git-hooks
hooks=("commit-msg" "pre-commit")

for h in "${hooks[@]}"; do
    echo "cp ${hook_dir}/${h} ${root_dir}/.git/hooks/"
    cp ${hook_dir}/${h} ${root_dir}/.git/hooks/

    echo "chmod +x ${root_dir}/.git/hooks/${h}"
    chmod +x ${root_dir}/.git/hooks/${h}
done

echo ""
echo -e "${GREEN}Installation is complete!${NC}"
