project: GENE-X
favicon: ../img/genex_icon.png
author: the GENE-X team
author_description: [list of contributors](page/contributors.html)
src_dir: ../src/
media_dir: ../img/
print_creation_date: true
search: true
extensions: pf //
            f90
graph: false
coloured_edges: false

<img style="float: right;" src="media/genex.png" width="200">

GENE-X is an Eulerian-type “continuum” code that solves the
gyrokinetic Vlasov equation on a grid. It is especially targeted
towards edge and scrape-off layer simulations and implements a
collisional, full-f, electromagnetic, gyrokinetic turbulence model.
GENE-X is based on the flux-coordinate independent (FCI) approach,
implemented in the subproject
[PARALLAX](https://gitlab.mpcdf.mpg.de/phoenix-public/parallax).

GENE-X is still in development and a lot of changes are to be expected.
We therefore **do not provide a manual yet**. Please consider the
[bibliography](page/genex.bib)
for the underlying model and numerics.

**This page provides the documentation for the source code itself. For other
documentation, please consider the following pages**

* The code repository can be found at:
[gitlab project page](https://gitlab.mpcdf.mpg.de/phoenix-public/genex)
* The wiki can be found at:
[wiki page](https://phoenix-public.pages.mpcdf.de/genex-wiki/)
