################################################################################
## Options and configurations for job submission of every case
## Array format:
## geometryN: [resolution1, resolution2, ..., resolutionN]
################################################################################
job_configurations:
  general:
    job_name: genex
    output_file: job.out
    runtime_modes: [cpu, cxx, acc, ompx]
    environment_commands:
      - BUILD_DIR=<GENEX_BUILD_DIR>
      - module purge
      - source ${BUILD_DIR}/toolchain.sh
      - ''
      - export SRUN_CPUS_PER_TASK=$SLURM_CPUS_PER_TASK
      - export OMP_NUM_THREADS=${SLURM_CPUS_PER_TASK}
      - export OMP_PLACES=cores
      - export OMP_PROC_BIND=close
      - export KMP_AFFINITY=noverbose

    execution_commands:
      - srun -Q ${BUILD_DIR}/bin/genex <GPU_FLAG> -o <OUT_DIR> <PARAMS_IN_FILE>

  cpu:
    partition_type: cpu

    n_procs:
      slab     : [1, 1, 16, 128]
      circular : [1, 4, 64, 256]
      salpha   : [1, 4, 64, 256]
      dommaschk: [2, 8, 64, 256]

    time_limits:
      slab     : [00:30:00, 00:30:00, 00:30:00, 02:00:00]
      circular : [00:30:00, 00:30:00, 00:30:00, 05:00:00]
      salpha   : [00:30:00, 00:30:00, 00:30:00, 05:30:00]
      dommaschk: [00:30:00, 00:30:00, 01:00:00, 20:00:00]

  cxx:
    params_gpu_offload:
      use_gpu_offload: .true.
      gpu_offload_backend: 0

    partition_type: gpu

    n_procs:
      slab     : [1, 1, 16, 128]
      circular : [1, 4, 64, 256]
      salpha   : [1, 4, 64, 256]
      dommaschk: [2, 8, 64, 256]

    time_limits:
      slab     : [00:30:00, 00:30:00, 00:30:00, 02:00:00]
      circular : [00:30:00, 00:30:00, 00:30:00, 05:00:00]
      salpha   : [00:30:00, 00:30:00, 00:30:00, 05:30:00]
      dommaschk: [00:30:00, 00:30:00, 01:00:00, 20:00:00]

  acc:
    params_gpu_offload:
      use_gpu_offload: .true.
      gpu_offload_backend: 1

    partition_type: gpu

    n_procs:
      slab     : [1, 1, 16, 128]
      circular : [1, 4, 64, 256]
      salpha   : [1, 4, 64, 256]
      dommaschk: [2, 8, 64, 256]

    time_limits:
      slab     : [00:30:00, 00:30:00, 00:30:00, 02:00:00]
      circular : [00:30:00, 00:30:00, 00:30:00, 05:00:00]
      salpha   : [00:30:00, 00:30:00, 00:30:00, 05:30:00]
      dommaschk: [00:30:00, 00:30:00, 01:00:00, 20:00:00]

    environment_commands:
      - export NVCOMPILER_ACC_DEVICE_TYPE=NVIDIA

  ompx:
    params_gpu_offload:
      use_gpu_offload: .true.
      gpu_offload_backend: 2

    partition_type: gpu

    n_procs:
      slab     : [1, 1, 16, 128]
      circular : [1, 4, 64, 256]
      salpha   : [1, 4, 64, 256]
      dommaschk: [2, 8, 64, 256]

    time_limits:
      slab     : [00:30:00, 00:30:00, 00:30:00, 02:00:00]
      circular : [00:30:00, 00:30:00, 00:30:00, 05:00:00]
      salpha   : [00:30:00, 00:30:00, 00:30:00, 05:30:00]
      dommaschk: [00:30:00, 00:30:00, 01:00:00, 20:00:00]

    environment_commands:
      - export OMP_TARGET_OFFLOAD=MANDATORY
      - export OMP_STACKSIZE=256M
