target_sources(GENEXCore-Library
    PRIVATE
        ${CMAKE_CURRENT_LIST_DIR}/op_base_m.f90
        ${CMAKE_CURRENT_LIST_DIR}/op_bnd_cond_m.f90
        ${CMAKE_CURRENT_LIST_DIR}/op_bnd_cond_s.f90
        ${CMAKE_CURRENT_LIST_DIR}/op_bnd_cond_dir_cpu_s.f90
        ${CMAKE_CURRENT_LIST_DIR}/op_bnd_cond_neum_cpu_s.f90
        ${CMAKE_CURRENT_LIST_DIR}/op_rhs_vlasov_eq_static_m.f90
        ${CMAKE_CURRENT_LIST_DIR}/op_rhs_vlasov_eq_static_s.f90
        ${CMAKE_CURRENT_LIST_DIR}/op_rhs_vlasov_eq_static_cpu_s.f90
        ${CMAKE_CURRENT_LIST_DIR}/op_rhs_vlasov_eq_static_bsg_cpu_s.f90
        ${CMAKE_CURRENT_LIST_DIR}/op_rhs_vlasov_eq_dynamic_m.f90
        ${CMAKE_CURRENT_LIST_DIR}/op_rhs_vlasov_eq_dynamic_cpu_s.f90
        ${CMAKE_CURRENT_LIST_DIR}/op_mom_maxwells_eq_m.f90
        ${CMAKE_CURRENT_LIST_DIR}/op_mom_maxwells_eq_cpu_s.f90
        ${CMAKE_CURRENT_LIST_DIR}/op_mom_ohms_law_m.f90
        ${CMAKE_CURRENT_LIST_DIR}/op_mom_ohms_law_cpu_s.f90
        ${CMAKE_CURRENT_LIST_DIR}/op_set_initial_condition_m.f90
        ${CMAKE_CURRENT_LIST_DIR}/op_set_initial_condition_s.f90
        ${CMAKE_CURRENT_LIST_DIR}/op_set_initial_condition_cpu_s.f90
        ${CMAKE_CURRENT_LIST_DIR}/op_sheath_m.f90
        ${CMAKE_CURRENT_LIST_DIR}/op_sheath_cpu_s.f90
        ${CMAKE_CURRENT_LIST_DIR}/perf_counter_m.f90
        ${CMAKE_CURRENT_LIST_DIR}/timer_m.f90
)

if(ENABLE_GPU)
    target_sources(GENEXCore-Library
        PRIVATE
            ${CMAKE_CURRENT_LIST_DIR}/op_rhs_vlasov_eq_static_gpu_s.f90
            ${CMAKE_CURRENT_LIST_DIR}/op_rhs_vlasov_eq_dynamic_gpu_s.f90
            ${CMAKE_CURRENT_LIST_DIR}/op_mom_maxwells_eq_gpu_s.f90
            ${CMAKE_CURRENT_LIST_DIR}/op_mom_ohms_law_gpu_s.f90
            ${CMAKE_CURRENT_LIST_DIR}/op_bnd_cond_dir_gpu_s.f90
            ${CMAKE_CURRENT_LIST_DIR}/op_bnd_cond_neum_gpu_s.f90
    )
endif()

add_subdirectory(arithmetic_operators)
add_subdirectory(collisions)
add_subdirectory(diagnostics)
add_subdirectory(field_solve_operators)
add_subdirectory(mms)
add_subdirectory(neutrals)
add_subdirectory(sources)
add_subdirectory(vspectral)

if(ENABLE_UTESTS)
    add_subdirectory(tests)
endif()
